import React, { useEffect, useState, useContext } from "react";
import { UserState } from "../utils/UserState";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";
import Link from "next/link";

export default function Layout({ title, children }) {
  const [cartItemCount, setCartItemCount] = useState(0);
  const { state, dispatch } = useContext(UserState);
  const { cart } = state;

  useEffect(() => {
    setCartItemCount(cart.cartItems.reduce((a, c) => (a += c.quantity), 0));
  }, [cart.cartItems]);

  return (
    <>
      <Head>
        <title>
          {title ? title + " Example-shopping-site" : "Example-shopping-site"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer limit={3} position="top-center" />

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center justify-between shadow-md px-4 bg-orange-300">
            <Link href="/">
              <a className="text-lg font-bold">Example Shopping Site</a>
            </Link>
            <div>
              <Link href="/Cart">
                <a className="p-1">Cart {cartItemCount > 0 && <span className="rounded-full bg-white px-3">{cartItemCount}</span>}</a>
              </Link>
              <Link href="/login">
                <a className="p-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner bg-white mt-4">
          CopyRight Example Shopping Site
        </footer>
      </div>
    </>
  );
}
